name: Tests

on:
  pull_request:
    branches:
      - main
      - dev
  push:
    branches:
      - dev

jobs:
  test:
    name: Correr tests con AVA
    runs-on: ubuntu-latest

    steps:
      - name: Checkout del repositorio
        uses: actions/checkout@v4

      - name: Instalar Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Instalar pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 9
          run_install: false

      - name: Obtener directorio del store de pnpm
        id: pnpm-cache
        run: echo "STORE_PATH=$(pnpm store path)" >> $GITHUB_OUTPUT

      - name: Configurar cache de pnpm
        uses: actions/cache@v4
        with:
          path: ${{ steps.pnpm-cache.outputs.STORE_PATH }}
          key: ${{ runner.os }}-pnpm-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-

      - name: Instalar dependencias
        run: pnpm install

      - name: Correr tests
        run: pnpm test